version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

install:
  - cmd: cd %LOCALAPPDATA%
  - ps: (New-Object Net.WebClient).DownloadFile("https://github.com/atom/atom/releases/download/$((Invoke-RestMethod -Method Get -Uri 'https://api.github.com/repos/atom/atom/releases/latest' | Select-Object tag_name).tag_name)/atom-windows.zip", "$(pwd)\atom-windows.zip")
  - cmd: 7z -y x atom-windows.zip

build_script:
  - cmd: SET PATH=%LOCALAPPDATA%\Atom\resources\app\apm\bin;%PATH%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: apm clean
  - cmd: apm install
  - cmd: apm test --path %LOCALAPPDATA%\Atom\resources\cli\atom.cmd
